export enum ActionTypes {
    ARTICLES_REQUESTED = 'ARTICLES_REQUESTED',
    ARTICLES_LOADED = 'ARTICLES_LOADED',
    ARTICLE_REQUESTED = 'ARTICLE_REQUESTED',
    ARTICLE_LOADED = 'ARTICLE_LOADED',
    API_ERRORED = 'API_ERRORED',
}